### ISSUE TITLE
Seeking new maintainer

### ISSUE THREAD

**Issue by nalgeon** [nalgeon/iuliia-js#14]
I'm not really into the modern JS / TS. So I very much would like to transfer `iuliia-js` to someone both capable and willing to take good care of it.

To-do, as I see it:

- Update the dependencies (they are kinda obsolete)
- Fix the CI (move from the broken Travis to the GitHub Actions)
- Maybe finish the [Tree shaking](https://github.com/nalgeon/iuliia-js/pull/13) feature

**Comment by corporateanon** [comment]
Hey! I could try. I am into modern TS and I love GH Actions.
I can setup release-based publishing to NPM.

**Comment by nalgeon** [comment]
@corporateanon is taking care of `iuliia-js` now! 🎉
