### ISSUE TITLE
Import only demand schema. For smaller vendor size.

### ISSUE THREAD

**Issue by adinvadim** [nalgeon/iuliia-js#2]
For example:
import iuliia from "iuliia";
import ICAO_DOC_9303 from 'iuliia/schemas/ICAO_DOC_9303';
iuliia.translate("Юлия Щеглова", ICAO_DOC_9303);

**Comment by nalgeon** [comment]
Unfortunately, my JS bundling skills are close to non-existing. You are welcome to send a PR though.

**Comment by nalgeon** [comment]
Done in [0.7.0](https://www.npmjs.com/package/iuliia/v/0.7.0) for `mosmetro` and `yandex_money` schemas.

**Comment by corporateanon** [comment]
I created a PR which compiles `iuliia` to ESM, which can be easily optimized by Webpack with tree-shaking on. #26

**Comment by corporateanon** [comment]
Now `iuliia@0.8.2` can be tree-shaked in your project with any modern bundler.

For webpack the following options should be set in config:

```
    optimization: {
        innerGraph: true,
        usedExports: true,
    }
```
